# Github Actions Ci to check if the naming of commits matches the pattern "date: description"
# This workflow is triggered on pull requests to the master branch.
name: Naming
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check commit message
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^\d{4}-\d{2}-\d{2}: .+'
          error: 'The commit message does not match the pattern "date: description"'
          flags: 'gm'